import {StyleSheet} from "react-native";
const styles = StyleSheet.create({
 container:{
     width:'100%',
     height:"100%",
 },
 Heading:{
    width:"100%",
    alignItems:'center'
 },
 img:{
     marginTop:30,
  width:180,
  height:160,
   alignItems:'center',
 },
 Textdesign:{
  color:'#fff',
  fontSize:16,
  marginTop:46,
  marginLeft:20,
  textAlign:'center',
  marginBottom:40,
 },
 loginemail:{
     width:'85%',
     height:45,
  backgroundColor:'#fff',
  borderRadius:8,
  shadowColor: '#001818',
  shadowOpacity: 4.59,
  shadowRadius: 8.22,
  shadowOffset:{
  width:1,
  height:5,
  },
  elevation:8,
  marginTop:15,
  marginLeft:25,
 },
 google:{
     flexDirection:'row',
     alignItems:'center',
    justifyContent:'center',
     marginTop:12,
},
imgg:{
 height:20,
 width:20,
},
 loginEmailText:{
     color:'#5d6475',
  fontSize:15,
  fontWeight:'700',
  marginLeft:8,
 },
 fb:{
 flexDirection:'row',
 alignItems:'center',
 justifyContent:'center',
 marginTop:12,
 },
 loginEmailfbText:{
    color:'#5d6475',
    fontSize:15,
    fontWeight:'700',
    marginLeft:8,
 },
 phone:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center',
    marginTop:12,
    },
    loginEmailphText:{
       color:'#5d6475',
       fontSize:15,
       fontWeight:'700',
       marginLeft:8,
    },
    logtext:{
        fontSize:16,
        color:'#fff',
        marginTop:50,
        marginLeft:19,
        textAlign:'center',
    }
});
export default styles;
